import type { Metadata } from "next";
import { Aldrich, Host_Grotesk } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/sidebar/Navbar";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { ThemeProvider } from "@/contexts/ThemeContext";

const aldrich = Aldrich({
  variable: "--font-aldrich",
  subsets: ["latin"],
  weight: "400"
});

const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-host-grotesk"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${hostGrotesk.variable} ${aldrich.variable} antialiased`}
      >
        <ThemeProvider>
          <LanguageProvider>
            <Navbar
              logo={{
                src: "/logo.svg",
                alt: "Logo"
              }}
            />
            {children}
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
